# /etc/ugreen-leds.conf
# 绿联DX4600 Pro前面板LED控制配置文件

# =========== 磁盘活动监控参数 =========== 

# 磁盘与LED的映射方法: ata, hctl, serial
# 建议使用 serial (通过序列号映射)，最稳定
MAPPING_METHOD=serial

# 编译好的磁盘监控程序路径 (可选)
BLINK_MON_PATH=/usr/bin/ugreen-blink-disk

# 编译好的待机监控程序路径 (可选)
STANDBY_MON_PATH=/usr/bin/ugreen-check-standby

# 磁盘待机检查间隔 (默认: 1 秒)
STANDBY_CHECK_INTERVAL=1
# LED 反转模式 (0=活动时亮, 1=活动时灭)
LED_INVERT=1

# 磁盘序列号 (仅当 MAPPING_METHOD=serial 时使用)
# 请根据你的物理硬盘槽位顺序填写序列号
# 格式: "槽位1序列号 槽位2序列号 槽位3序列号 槽位4序列号"
DISK_SERIAL="Z1ZAV6FB WD-WMC4N0H8E8VL \"\" \"\""

# 磁盘活动检查间隔 (默认: 0.1 秒)
LED_REFRESH_INTERVAL=0.1

# 磁盘LED亮度，取值范围 1-255 (默认: 255)
BRIGHTNESS_DISK_LEDS="255"

# 健康磁盘的颜色 (默认: 白色)
COLOR_DISK_HEALTH="255 255 255"

# 不可用磁盘的颜色 (默认: 红色)
COLOR_DISK_UNAVAIL="255 0 0"

# 待机模式磁盘的颜色 (默认: 蓝色)
COLOR_DISK_STANDBY="0 0 255"

# ZPOOL失败设备的颜色 (默认: 红色)
COLOR_ZPOOL_FAIL="255 0 0"

# SMART信息不健康的颜色 (默认: 红色)
COLOR_SMART_FAIL="255 0 0"

# 使用smartctl检查磁盘健康 (默认: 开启)
CHECK_SMART=true

# SMART检查间隔 (默认: 360 秒)
CHECK_SMART_INTERVAL=360

# 检查ZPOOL健康状态 (默认: 关闭，如果你没用ZFS可以保持关闭)
CHECK_ZPOOL=false

# ZPOOL检查间隔 (默认: 5 秒)
CHECK_ZPOOL_INTERVAL=5

# 磁盘在线状态检查间隔 (默认: 5 秒)
CHECK_DISK_ONLINE_INTERVAL=5


# =========== 网络活动监控参数 =========== 

# 发送数据时闪烁网络灯 (默认: 1-开启)
NETDEV_BLINK_TX=1

# 接收数据时闪烁网络灯 (默认: 1-开启)
NETDEV_BLINK_RX=1

# 网络灯闪烁周期 (默认: 200 毫秒)
NETDEV_BLINK_INTERVAL=200

# 网络正常状态下的颜色 (当 CHECK_LINK_SPEED=false 时使用)
COLOR_NETDEV_NORMAL="255 165 0"

# 网络连接/速度监控间隔 (默认: 60 秒)
CHECK_NETDEV_INTERVAL=60

# 监控网关连通性 (默认: 关闭)
CHECK_GATEWAY_CONNECTIVITY=false

# 监控链路速度 (默认: 关闭)
CHECK_LINK_SPEED=false

# 网络LED亮度，取值范围 1-255 (默认: 255)
BRIGHTNESS_NETDEV_LED="255"

# 不同链路速度下的颜色 (当 CHECK_LINK_SPEED=true 时使用)
COLOR_NETDEV_LINK_100="0 255 0"
COLOR_NETDEV_LINK_1000="0 0 255"
COLOR_NETDEV_LINK_2500="255 255 0"
COLOR_NETDEV_LINK_10000="255 255 255"

# 动态监控链路速度并计算颜色 (默认: 关闭)
CHECK_LINK_SPEED_DYNAMIC=false

# 最低速度对应的颜色 (默认: 红色)
CHECK_LINK_SPEED_DYNAMIC_COLOR_LOW="255 0 0"
# 最高速度对应的颜色 (默认: 绿色)
CHECK_LINK_SPEED_DYNAMIC_COLOR_HIGH="0 255 0"
# 最低速度阈值 (默认: 0)
CHECK_LINK_SPEED_DYNAMIC_SPEED_LOW=0
# 最高速度阈值 (默认: 10000)
CHECK_LINK_SPEED_DYNAMIC_SPEED_HIGH=10000

# 无法Ping通网关时的网络灯颜色
COLOR_NETDEV_GATEWAY_UNREACHABLE="255 0 0"

# =========== 电源LED参数 =========== 

# 电源LED闪烁设置
# * none: 不闪烁 (默认)
# * breath <亮时间> <灭时间>: 呼吸效果
# * blink <亮时间> <灭时间>: 闪烁效果
BLINK_TYPE_POWER="none"

# 电源LED亮度 (默认: 255)
BRIGHTNESS_POWER="255"

# 电源LED颜色 (默认: 白色)
COLOR_POWER="16 193 69"
